context:
  version: "2.16.8"

package:
  name: astro-ls
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@astrojs/language-server/-/language-server-${{ version }}.tgz
  sha256: 2e23a997ad2f646376158a8bd7697b6d8df136508c68ef294a67be8e0419b347

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "astro-ls 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for Astro
  homepage: https://github.com/withastro/language-tools
  repository: https://github.com/withastro/language-tools

extra:
  recipe-maintainers:
    - danielnachun
