context:
  version: "2.16.13"

package:
  name: astro-ls
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@astrojs/language-server/-/language-server-${{ version }}.tgz
  sha256: d889834a4e1dacaadccc481d05509180219ae4c0c0e0a44d952ddbf03d2a49ee

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "astro-ls 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for Astro
  homepage: https://github.com/withastro/language-tools
  repository: https://github.com/withastro/language-tools

extra:
  recipe-maintainers:
    - danielnachun
