context:
  version: "2.17.1"

package:
  name: astro-ls
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@astrojs/language-server/-/language-server-${{ version }}.tgz
  sha256: 748945e5aef4251ed89fa557472f7cf93204eba8cb77475cdd38f8099b2343eb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "astro-ls 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for Astro
  homepage: https://github.com/withastro/language-tools
  repository: https://github.com/withastro/language-tools

extra:
  recipe-maintainers:
    - danielnachun
