context:
  version: "2.15.4"

package:
  name: astro-ls
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@astrojs/language-server/-/language-server-${{ version }}.tgz
  sha256: c7d463c40c488c0315056cda65c50299db3cb57bb155a6429d32f184688529db

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "astro-ls 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for Astro
  homepage: https://github.com/withastro/language-tools
  repository: https://github.com/withastro/language-tools

extra:
  recipe-maintainers:
    - danielnachun
